#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
@author:       Ivan Fontarensky
@license:      GNU General Public License 3.0
@contact:      ivan.fontarensky_at_gmail.com
"""


__author__ = 'ifontarensky'


SNORT_XPM = [
"64 64 186 2",
"   c #3E3E3F",
".  c #3F3F40",
"X  c #3F4041",
"o  c #424243",
"O  c #464748",
"+  c #484748",
"@  c #4C4A4B",
"#  c #514C4D",
"$  c #544F50",
"%  c #5C4F51",
"&  c #555253",
"*  c #5B5354",
"=  c #595758",
"-  c #5C5A5B",
";  c #625455",
":  c #655758",
">  c #695759",
",  c #645C5C",
"<  c #6C5C5D",
"1  c #735B5E",
"2  c #5F5F60",
"3  c #655F60",
"4  c #685F60",
"5  c #745F60",
"6  c #656263",
"7  c #6B6364",
"8  c #6F6768",
"9  c #6C6B6B",
"0  c #746263",
"q  c #7B6465",
"w  c #756768",
"e  c #746B6C",
"r  c #7A6C6D",
"t  c #756F70",
"y  c #757273",
"u  c #7A7374",
"i  c #787778",
"p  c #7C7B7B",
"a  c #816466",
"s  c #836668",
"d  c #88676A",
"f  c #846A6C",
"g  c #8A6B6D",
"h  c #806F70",
"j  c #8D6F71",
"k  c #946E70",
"l  c #996F72",
"z  c #827374",
"x  c #8C7374",
"c  c #827778",
"v  c #837B7B",
"b  c #8A7C7C",
"n  c #927374",
"m  c #957778",
"M  c #9B7779",
"N  c #9B797B",
"B  c #A57477",
"V  c #A77679",
"C  c #A97679",
"Z  c #A17D7F",
"A  c #AC7A7D",
"S  c #B17B7E",
"D  c #7F7F80",
"F  c #807F80",
"G  c #A47F80",
"H  c #B47D81",
"J  c #B87E82",
"K  c #848384",
"L  c #8B8383",
"P  c #8B8788",
"I  c #8E8C8D",
"U  c #938484",
"Y  c #948788",
"T  c #9B8788",
"R  c #938A8B",
"E  c #9A8B8B",
"W  c #939293",
"Q  c #9E9393",
"!  c #9B9B9B",
"~  c #A78082",
"^  c #AB8385",
"/  c #A38E8E",
"(  c #AF8C8D",
")  c #B08587",
"_  c #BB8084",
"`  c #B28788",
"'  c #B5898B",
"]  c #BB8C8E",
"[  c #BF8F91",
"{  c #A39393",
"}  c #AC9696",
"|  c #A39D9E",
" . c #AC9D9D",
".. c #B39394",
"X. c #BF9092",
"o. c #B49D9D",
"O. c #BD9C9D",
"+. c #A09FA0",
"@. c #A4A3A3",
"#. c #ADADAD",
"$. c #B4A3A3",
"%. c #BBA3A3",
"&. c #B9A7A8",
"*. c #BDAAAA",
"=. c #AFB0B0",
"-. c #B3B3B3",
";. c #B8B7B7",
":. c #B7B8B9",
">. c #BBBBBB",
",. c #C18387",
"<. c #C58589",
"1. c #CB878B",
"2. c #C48B8E",
"3. c #CC888D",
"4. c #D18A8F",
"5. c #C68F92",
"6. c #CE8E91",
"7. c #D58C91",
"8. c #DA8E94",
"9. c #C49294",
"0. c #C89597",
"q. c #CB9799",
"w. c #CE999B",
"e. c #D39194",
"r. c #DE9196",
"t. c #DE9599",
"y. c #D29B9D",
"u. c #DF9A9D",
"i. c #E09196",
"p. c #E0969A",
"a. c #E09A9D",
"s. c #D89FA1",
"d. c #E09EA1",
"f. c #C1A6A5",
"g. c #CEA4A5",
"h. c #C2ADAE",
"j. c #CBADAC",
"k. c #DBA2A4",
"l. c #DEAFB0",
"z. c #C6B3B3",
"x. c #C0BFBF",
"c. c #CCB8B8",
"v. c #D2B2B2",
"b. c #DFB5B6",
"n. c #DAB8B7",
"m. c #D3BCBC",
"M. c #DDBBBA",
"N. c #E1A3A6",
"B. c #E3A7A9",
"V. c #E4A9AB",
"C. c #E3AFB0",
"Z. c #E6B2B4",
"A. c #E2BEBD",
"S. c #E9B9BB",
"D. c #E5C0BF",
"F. c #C0BFC0",
"G. c #C3C3C3",
"H. c #C8C7C8",
"J. c #CBCBCB",
"K. c #D6C1C2",
"L. c #DBC3C3",
"P. c #DDC8C8",
"I. c #CFD0D0",
"U. c #D3D3D3",
"Y. c #DCDCDC",
"T. c #E6C2C1",
"R. c #ECC5C4",
"E. c #EDC8C7",
"W. c #E2C7C8",
"Q. c #E3CCCC",
"!. c #EDCCCB",
"~. c #F0CDCC",
"^. c #EFD0CF",
"/. c #F0D0CF",
"(. c #E7D0D0",
"). c #ECD3D3",
"_. c #EFD8D8",
"`. c #F1D3D3",
"'. c #F2DADA",
"]. c #E3E3E3",
"[. c #E7E7E8",
"{. c #E8E7E8",
"}. c #EBEBEB",
"|. c #F0EFF0",
" X c #F4F4F4",
".X c #FEFEFE",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X X.X.X.X.X.X.X.X.X.X X.X",
".X.X.X.X.X.X.X X.X.X.X.X.X.X.X.X.X.X X.X.X.X.X.X.X.X X.X.X.X.X.X.X.X.X.X.X.X.X.X.X X.X.X.X.X.X.X X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X X.X.X.X.X.X.X",
".X.X X.X.X X.X.X X.X.X.X.X X.X.X.X.X.X.X.X.X.X.X.X.X X.X.X.X X.X X.X.X.X.X X.X.X.X.X X.X.X.X.X.X.X X.X.X.X X.X.X.X.X.X.X.X.X.X X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X|.>.U..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.XY.K @ W .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X X>.G.J.J.#.8 0 f 6 U..X.X X}.U.J.J.]. X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X].= & , = & g y.y.q @.[.:.K t 0 7 7 8 y #.}..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X[.- 1 ] ' 9.N.B.N.X.w y q M ] 0.y.q.' g % p Y..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X}.y < k.V.B.B.q.] u.' ] k.B.B.B.V.Z.Z.b.O.> p ]..X}.=.;..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.XI * q.B.V.B.G A a.B.B.B.B.B.V.l.} y y m.v.4 ! H.E 0 9 [..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X#.& 9.V.B.y.g <.a.B.B.B.B.Z.R.E R &.7 $.'.O., h 0.0.: >..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.XG.& ] V.B.^ d 7.t.N.B.B.B.Z.%.R Q.'.R } _.E.x 0 y.s.m p  X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X@.@ ~ V.y.q V r.u.N.B.B.k.C.L.).'.c.y L &.!.( : 0 d k - J..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X-., # n k.N q 4.t.N.B.B.B.B.B.E.'.(.Y y  .%.&...e -.@.! ! Y..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.Xx.7 C l $ 1 ; S t.N.B.B.B.N.B.B.Z.^.Q.L { ).Q T ' I .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.XH.e S r.3.l g H t.B.B.B.B.B.B.B.B.B.Z.E.c.Q.'.h.g.[ c J.}..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.XY.y B r.r.r.r.8.p.k.B.B.B.B.B.B.B.B.B.B.V.Z.S.S.Z.V.k.` x v +.G.Y. X.X.X.X.X.X.X.X.X.X.X.X X X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X X.X XR d 8.r.r.r.r.r.a.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.V.s.5.m r 7 y I @.-.>.G.J.J.G.>.-.! p i I >.}..X.X.X.X.X.X",
".X.X}.#.K F R I : ,.i.r.r.r.r.r.u.V.B.B.B.B.B.V.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.s.9.G f < : = = & * $ @ o   . .   + I  X.X X}. X.X",
".X}.p @ q ^ ` m < _ r.8.r.r.8.r.u.B.B.B.B.B.B.B.B.V.B.B.B.B.B.B.V.B.B.B.B.B.B.B.B.B.k.s.0.9.] ^ m 4 ; 7 c T Y 7 o @ >. X@.y p ;.",
".X-.+ x k.V.B.B.0.5.r.r.r.r.r.r.k.B.B.B.B.B.B.V.B.B.B.B.B.B.B.V.B.B.B.B.V.B.B.B.B.B.B.B.V.B.9.x z / j.D.R./.'.K.6   ! #.7 y 6 & ",
".X-.# ) V.V.B.B.B.B.N.p.r.r.r.r.N.N.B.B.B.B.B.B.B.B.V.N.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.9.j w / n.R.R.D.R.!.'._.b   W ! K 6 9 p ",
".X}.W r ~ w.k.B.B.B.B.d.t.r.r.t.N.V.N.V.B.V.V.N.B.B.V.B.B.V.V.N.B.B.V.B.B.B.V.B.B.B.s.G 4 b j.R.E.j.T T M.E.`.'.L o ;.#.9 W D 9 ",
".X.X Xx.6 ; n 5.u.u.N.B.k.t.t.u.B.B.N.V.B.B.V.B.B.B.V.B.B.B.V.B.B.B.B.B.B.B.B.B.B.y.g , } D.~.D.Q 7 T j.T.E.'._.u - Y.}.I K p @.",
".X.X.X@.* g ,.8.8.r.t.B.B.k.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.V.B.B.B.0.q 7 $.R.~.m.c O c D.E.R.!.Q.Q.6 K  X.X X].[..X",
".X.XJ., C 8.r.i.r.r.t.B.B.V.B.B.B.B.B.B.B.B.B.B.V.B.B.B.V.B.B.V.B.B.B.B.B.B.B.X.5 e j.E.^.z.8 o , j.E.R.v.o.&.*.- >..X.X.X.X.X.X",
".X Xp g 8.i.i.r.t.a.B.N.B.B.V.B.B.B.B.B.B.B.B.B.B.B.B.V.B.B.B.B.B.B.B.B.B.B.] : r v.E.).*., . + { R.S.o.7  .).R p |..X.X.X.X.X.X",
".XJ.< ,.i.8.i.p.N.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.9.: e v.R.`.z., . . e A.D./ & t Q.L.e x..X.X.X.X.X.X.X",
".XW q 8.r.r.r.N.B.B.B.B.B.B.B.B.B.B.B.a.a.d.B.B.B.B.B.B.B.B.B.B.B.B.B.B.0.< e v.E.^.z., X o - j.M.b + = z.'.E I  X.X.X.X.X.X.X.X",
"[.e C i.r.r.t.B.B.B.B.B.B.B.B.B.B.B.a.r.r.r.p.d.B.B.B.B.B.B.B.B.B.B.B.y.5 , j.R./.K.7 . o @ } A.U o o E _.m.i U..X.X.X.X.X.X.X.X",
"I.6 _ i.r.r.r.u.k.B.B.B.B.B.B.B.B.B.d.r.1.S 7.p.u.B.B.B.B.B.B.B.B.B.k.x * $.R.~.Q.u o o + U A./ @ o r P.).Y @..X.X.X.X.X.X.X.X.X",
"F.0 3.r.r.r.r.r.t.B.B.V.B.B.B.B.B.k.B.d.6.a d 4.r.u.N.B.B.B.B.B.B.B.~ & / R.E.!.U O . o v A.o.& . 6 m.'.$.K [..X.X.X.X.X.X.X.X.X",
"G.7 3.i.i.i.i.r.t.B.B.B.B.B.B.V.B.B.B.B.N.2.> 1 1.r.t.k.B.B.B.B.B.2.; c M.R.). .@ o o r M.j.,   & *.'.K.c H..X.X.X.X.X.X.X.X.X.X",
"I.6 J i.8.<.<.t.N.B.B.B.B.B.B.B.B.B.k.q.k.N.A + 1 1.r.t.a.B.B.d.e.0 < v.R.`.h.* . . 7 v.n.e o @ { '.Q.F @..X.X.X.X.X.X.X.X.X.X.X",
"|.F 1 ,.V f ] k.B.B.k.N.B.B.V.B.N.B.` x k.B.e.> o 1 3.r.r.p.p.r.B & } R.~.L.7 X . , j.D.U o o F )._.E K }..X.X.X.X.X.X.X.X.X.X.X",
".XH.= % g q.B.B.B.a.t.r.t.B.B.B.B.B.0.y.B.N.6.: + @ d 7.r.r.r.3.> r A.R.!.R O X # o.R.%.&   w L._. .t U..X.X.X.X.X.X.X.X.X.X.X.X",
".XJ.= s y.B.B.B.t.r.r.8.r.d.B.B.B.B.B.B.N.p.S & ! ! & B r.r.r.k = f.E.~.z.& . @ { D.n.7 X 8 K.'.$.8 J..X.X.X.X.X.X.X.X.X.X.X.X.X",
"U.9 < y.B.B.k.) 4.i.r.r.r.t.a.N.N.B.B.a.t.4.< & J. XK * ,.i.<.* z D.E.!.c . @ / D.R.U O e m.'. .9 >..X.X.X.X.X.X.X.X.X.X.X.X.X.X",
"I O N V.B.q.f ; ,.i.i.8.i.8.i.i.t.p.p.r._ 5 % 1 I  XJ.= a 4.l & %.R.~.h.@ & { D.R.j.= r K._. .7 -..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
"v X 5 ` ~ E K - q S 1.4.4.4.4.7.4.1.H M v - * s p .X Xp # A 1 0 M.R.!.U : ..D.R.R.Y c P.).Q 2 -. X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
"I.K 9 L ;.}. XY.! K c z c x q 1 > ; p G.}.I.L K U..X.X>.O 1 ; U R.R.L.v o.E.R.R.M.{ P.Q.L - -. X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X X X X.X.X.X.X.X|.}.J.:.-.i X & s c Y..X.X X X.X.X.XY., o + } R.R.n.o.D.E.R.!.W.K.c.r 9 G..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X>.y z G m < > G ~ | .X.X.X.X.X.X.X.XI o O } R.E.D.M.E.E.`.'.Q.{ 2 p Y..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.XJ.- m y.X.Z ` ~ 1 d W  X.X.X.X.X.X.X.XG.& o b R.!.^.)./.`.`.z.e = +.{..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X;.# ^ B.N % & m ) : W .X.X.X.X.X.X.X.X XI o # $.)._._.Q.&.u & 9 >..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X}.I < ^ 0.` k # f ~ 0 J..X.X.X.X.X.X.X.X].K O & u c y 3 @ - @.]..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X X#.p y x j * & G g I  X.X.X.X.X.X.X.X.X}.@.9 - - 6 p #.]..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X|.U.F.F.H.! f ' p [..X.X.X.X.X.X.X.X.X.X}.].].|. X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.XU.r G P |..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.XY.z q ! .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X;.7 v Y..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.XI.i I ]..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X[.-.>. X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X X.X.X.X X.X.X.X.X.X.X X.X.X.X.X.X.X.X.X.X X.X.X X.X.X.X X.X.X.X.X.X.X X.X.X X.X.X.X.X.X.X.X.X.X X.X.X.X X.X.X.X.X.X.X X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
" X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X X.X.X.X.X.X.X X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X X.X.X.X.X.X.X X.X",
".X.X.X.X.X X.X.X.X.X.X.X.X.X X.X.X X.X.X.X.X.X.X.X.X.X X.X.X.X.X.X.X.X.X.X.X.X.X.X X.X.X.X.X.X.X.X.X.X X.X.X.X.X.X.X.X.X.X.X.X.X"]