#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
@author:       Ivan Fontarensky
@license:      GNU General Public License 3.0
@contact:      ivan.fontarensky_at_gmail.com
"""

__author__ = 'ifontarensky'


IOC_XPM = [
"186 103 66 1 ",
"  c #304D7F",
". c #304F81",
"X c #335183",
"o c #395686",
"O c #3B5887",
"+ c #365488",
"@ c #3A5689",
"# c #3D5989",
"$ c #415D8C",
"% c #435E90",
"& c #45618E",
"* c #48638F",
"= c #466191",
"- c #4B6691",
"; c #4E6993",
": c #526B96",
"> c #546C99",
", c #577098",
"< c #5B739B",
"1 c #60779E",
"2 c #62799F",
"3 c #5D75A0",
"4 c #667DA2",
"5 c #697EA4",
"6 c #6C81A6",
"7 c #6C81A8",
"8 c #7286A9",
"9 c #7589AB",
"0 c #798CAE",
"q c #7C8FB0",
"w c #7F91B0",
"e c #8395B4",
"r c #8698B5",
"t c #8899B6",
"y c #8597B8",
"u c #8698B8",
"i c #8C9DBB",
"p c #8FA0BD",
"a c #92A2BD",
"s c #94A3C0",
"d c #99A7C1",
"f c #9EACC4",
"g c #A1AEC7",
"h c #A3AFC8",
"j c #A3B1C7",
"k c #A4B1C9",
"l c #ACB7CC",
"z c #ADB9CE",
"x c #B0BBCF",
"c c #AFBAD0",
"v c #B1BCD1",
"b c #BBC5D6",
"n c #BBC5D8",
"m c #C7CFDD",
"M c #C7D0DD",
"N c #C9D0DE",
"B c #CCD3E1",
"V c #D6DCE6",
"C c #DADFE9",
"Z c #DFE3EB",
"A c #E3E7EF",
"S c #E4E8EF",
"D c #E6EAF0",
"F c #F1F3F7",
"G c #F2F4F8",
"H c gray100",
".. XX .  X   XX  o  X XXX X X X  XX  XX..Xo.XX    XX Xo   X XXXXXXX ... ..X XX X. ..X ..  XXX XX  . X...X  X  ...XX .......XX X .. o  o XX.o     XX X  X XXXX XX. .XX XXX ..  X X......XX ",
".  XX X.   X Xo        XXX X X X Xo XX...XoXoXX  X X.Xo  X.. XXXXXX  .X. XXXX X . ..X. ... .  X X . .  XX XXX... .X X......XXX ....+XXXXXX.  oXoo X X   XXo XX XX  X+. XX  .XXX.X... ..XX ",
". .XX.   X  XXo  X    XXX X .XX .Xo.Xo.XXXXXo X.  o   o  ....XXXXXX  .X .XX X..X . XX  .X .XXXX.       XX  X .X..XX.X. X...Xo.X....+XooXoXXX   Xo XXo X .XXXXX XX. XXX.XX    XX X.XX....X ",
"XXXXXXXX Xo XXXXXXXXXXXXO XXX X   X. XX. .XXXX  X     o ...  .X.XXX ...XXXXXXXXXXXXXoXX.XXXXXXXXXXXXXXXoXXXXXXXXXXXXXXXXXXXXX . ...XX   . X.X. X     X   X XX  X.  .X..XXX.XXXXXXXXX.X.XOX",
" X XXXX  X    X X   X X X..  X  ..X ..... X.XXX     X o  ...  XXX   . X X X.X.XX. ..X  X X.X XX.X. .XX XXX XXX X..X.X .. .   .. .. XX X X.X..  .X.. X  X XX X  X...XX..XX  XXXX X X X  XX ",
"XX  X X    oXoXX XX   XXX..   . ..X..o.. .XXo. ..X X XX    .  XXXXX .....XX XX X.  XX.  X .X XXX  . . .XX.XX  X .XX.XX.XX. XX  X ..X XX X....  XX ..X   ..X X  X.. .XXXXX X  XX X XX   XX ",
" X XX    X   XX X   X XXXXX   .......XX..XXXXX.  .    XX XX X     X  ..XX X.XXXX    XX  .X X  X... X  X.X.XXX .XX X X ...  XX  ....XXXo +.X.X   X   X X  . .X   .. X X.XXXX X   XXXXX   . ",
"XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX.oXX.+XXXXo..XX..XXXXXXX X  XXoXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX.XoXXXX+.XXXX.XXXX.XX XX..XXXXXXXXXXXXX+XXXXXXXXXXXXXX X.",
"XX X XXX XXXXXXXX X  XXXXXX X X  X.XXX..XXXXXXX   X   X X    XX  X XX X XX  X XXX XX XX X XXX X . XXX XXX XXXX XX X.XXXXXX.XX .XX..XXX .XX X.       X.  X X X    X  XX XXXXX  X XX X X  X.",
" ooooXOoXOo XXXoooooOoXOoXX.XoooXooXX#oXXXXooooXoXXXX X XoooXXo XoX  XX++XoOOoo+X X oXoXoOo+oO X.XXoooXOoXooXXXXOooooOOXooXX.XXOXXo@ooo+oXXooooXoooXoXX  XoooXoOXXooXXXoooooOooooXXX ooooX",
"XX XoXXXXXXXXooXXXXXX XXXXXXXX X oXX.XXXXXXoX X X X XXXXXX  XXXXXXXXXXXX oXXXX XXXX XXXX XXXX XXXXXXXXXXXX XXXXX XXX.XXX XX.XX.X...@..X.XXX .  XX. .X.X.X XXX XXX XXXX o XXXXXXXXXXXXX oo ",
"   XX X .    XX    X   XX .      XX .XXX XXXoXXXX XX XoX  X .X XX X    X X  X XX   X       X XXX    ...Xo  XX.    X..  .   XX. ....XXXo.XXXXXX.Xo. XX... XXX X XX  XX  oXX   XX XX X   XX ",
"XXXXX X  X ..Xo   . ...XX..      XX XXX   XXX       .Xo   .. . XX   X    Xo XX XX  XX  X  X  XX  X. .. XX  X   X.XXXX  . . XX X  . X Xo X..X ..XX   X  . XX     X XXo   X    Xo XX  .  XX ",
"   XX    ..  XX  . . .XXX... X X XXX XX  XXXo X    X XX  X . X Xo  X   X XX X XX  XXXX  X  X Xo    ... oX  X..   XX X   X  XX  X...XXXX X..... XX X X... XX X X        oX X X X X XX.  XX ",
"    X X .. . XX ....XXXXX..   . .XX. XX   XXXXX X.  .XX       .XX  X X  X X XXXXX  XX      oXXX   .....XX  XXX X XXXX   .  XX  X.  XX XXXX.... XX   X .  XX  X  X XXo  X X XXXX  X.XX  XX.",
"XXXXXX XXXX XXoXXXX..XXXX.X...X..XX. oX XXXXX X   X  XXXX X  X XXX.   XXXXX XXX X  XX X X XX  oXX......Xo .XX X XXXXX.XXX XXX. X. .o XX.XX...  XX  XX  .XXo    X   Xo  XX X X o XXXXX..Xo ",
" X Xo... X X oo  X XXXXXoX X X X oX  oX  .Xoo XX... .XX         XX  .. ..XX XXXX    o    X XXXo o    X XoX XXX.. XO o   X   O XX...X........X..XO   O    .O.....X  XX  o XX XXXXX    X XX.",
"XX XXX.X.XX XXX X X ..X.X X.  X.    .X. ..XXX     .  .o. O4tfMMHHHHHHMbp8$XXXXXXX   X X X XXX X   X X XX X XXX.XXXXX   XX    X 6iimmHHHHHHAmvi9;           ......  XX  XX  X XX  oo X XXX ",
"8q82lDHCCja4840062qprilggmDa0q42ee>58=XX$5e942rw*99o.orbDHHHHHHHHHHHHHHHHHDl581XXo:80628w2<9,XXO,895180<25*XX$,54<,88-<1& $qxZHHHHHHHHHHHHHHHHHHFj2 O   OOO.O. .X XXXX o  X XXXXXXXo   oo ",
" X6mHHHHHHHHHHHHHHHGHHHHHFr.  oX o$XXoX    oOoXXoXX<lFHHHHHHHHHGHHHHHHHHHHHHHN8XX  oooo XoXXooo    ooX $$ XX  ..oOOX O $rbHHHHHHHHHHHHHHHHHHHHHHHHHDp    X.OOXOOXXXXX  oooooOOoXO X XooOoX",
" $bHHHHHHHHHHHHHHHHHHHHVg:X      ..  o.   X X    4NHHHHHVNaaddpagNAHHHHHHHHHHHHm<  X      XX XXX   X  XX    . ..     ,lFHHHHHSNcsaasssscmFHHHHHHHHHHHB,   .X .   X X X XX X X..  X X X XX ",
" ..$0smNHHHHHHHHHHGfy6+X.X       .   ..        4NHHHAg5%   o   .XXX%9fZHHHHHHHHHHa         X       X        ...    2MHHHHna5XXXX..XX...XXX%0lFHHHHHHHHF,      ..    X XXX. XX..XoXXX      ",
"....XXXX++<AHHHHHA$X......  X   .....X..  XXX;bHHFz<oXXX X  .OXX.XXXXX+3cHHHHHHHHHV# XXX   XX X    XXXXX   X....X,MHHHbt$..........X..  XXXXXXyAHHHHHHGD.XXXXXXXXXXXXXXXXXXXX X  XXXX X  X",
"  X..XX..X.gHHHHHb  ..X...X   X .....X. XXXXaGHFa%XX  o XXX ............X;lHHHHHHHHF<  Xo  XX   X XX X X   oX..#fHHFf;  .......X...X.. XXX.X..X+aFHHHHHF..XX....X   X  X.. .X.X XXXX.X.XX ",
". XXXXX  X pHHHHHa X   XX . .. . o  .X... <VHHh%X....XX .X .....X.... ...Xo5VHHHHHHHF, ... XX X    XX..X...X..4AHHl%X.. ...... . ..X..X XXX  X   <FHHHHA O   X .  .XX  X X XXXX  o  X  oX ",
".. XXXX  X 0HHHHHa  XX XX....  . XX  o. .pHHA3X ... .Xo      . XX.... . .XX.+cHHHHHHHFo... X Xo  XXX   X.....aHHZ5+ .. .....X..... o.XX XX XX  o  6HHHHa XX   . X  XO  XX X  Xo X X X  XX ",
"  .XXX   X 5HHHHHpX  X XX....XX  oo .X.$bHHc=.X ..X. Xo  X  .. XX...X...XXo .XaHHHHHHHV$X .X XX    X X oX..$mHHn%Xo .. ....oo...  .XXXo  XX X  XO  CHHF$  O..  .  XXX  X X XXXX.XXX     X ",
"XXXXooXXXXX5HHHHH0XXXXXooXXXXXXXXXoXXo;VHHlooXX.X.XXXXo. XX .X.XX.....X.XXX.oXXtHHHHHHHf..XX oooXXX+XXXXo.<ZHHlXXX++X.XXXXXooX.oXXXXXXXXXXXXXXXoo  aHHz. O  X ..XX XXX XX X  oXXXXXXXXX XX",
"    XXX..X.5HHHHH5.X X  XXXXX XXXXX .<FHHhXXXXX . XX Xo .X.    .X....... XX XX XaHHHHHHH4   XXX   XXX  o.,GHHx+.XXoX  X X XXX.XX   .  XXXXXXX XXXXX5HH<X O. .      XX XXX ..XXX XXXo   oo ",
"  $$ooooXoX5HHHHH6Xoo$X$$ X Xooooo$o<FHHlXo#$ooo$oooXo$ .OOOXOOO@o. . .oooooooX$XzHHHHHHDooooOo  XXO+ooO3FHHlX .+@OoooooOo XoXX$$oo$$o$oXX ooooo$oX6HFX. OOOOXOOXXOXXX XooXoOOOXOoXX oO#OX",
"XX XXXX..X.5HHHHH5XXXX oX XX XXX.oo-GHHVX.Xoo.XX .X  oXXXX.X.X.Oo.X..... oX     X$SHHHHHHe X o  X  X X 1FHHV%..X.oo.XXXXX .ooXXX X X  oXXXXXXXXoXX..HnX..OO.  .XX  XX  X XX. .X         X ",
"X  XXXXXXX.4HHHHH5X.XX X XX X XX..$VHHF>..X.X ..  X.  X ..........Xo.oXXXX XXXXXX.5HHHHHHA XXXo  XXXXX#FHHH3X.XX.oXX X  XX XX.X.X XX oX X   X  XX ..H5..........Xo+XOXXXXXXXXXXX XXXo Xoo ",
" X oXXXX.. #HHHHH5.X X XXX    XX XzHHHa....XX.. ................X       X XXX...X..nHHHHHHeX oo  XXXX#VHHHaX....XXXX ..  . X   X....................j....O... .....X....X.X..X..X......XX.",
"   XXXX  X. HHHHH5.   XXX X  X   qHHHV....XXX.........O........Oo X X X  Xo X..XX .>HHHHHHM   o    X fHHHA#XX....XX    X. XXo  X......O.........O........... . .................XX.....XX.",
"     XX .X .HHHHH# .X        XX OFHHH5  .....  .................  X    o XX XXX ...XzHHHHHH; o X  XX4HHHHa X.... XX  X  .. X   X.....XX........X..........  .. ...........X.....X...X...X.",
" X   XXX.. .HHHHH.X.XXX XXXX XXXlHHHVXXX..XX..XXXXX.............XXX  X X    X  XX ..<HHHHHHa  X X  XAHHHF# X..XXX XX XXXX XXoXXXX..X........XXX............O...X................X.X.......",
"X    o  .. .HHHHH .. X.    . X -HHHHr.X  Xo X.XX................  X   X X X X X .X  .AHHHHHNX    . eHHHHa. X..     o  X X  X X X....X.X.O......X........ .......................X.XX......",
"X X  XX ....HHHHH. . X. X .  X bHHHH$.X X X ...X................ XX X     X XX  . X .aHHHHHH  X ..OFHHHH; .XX .XX          X  XX....X..X....X.X.........  ..............X.......X..XX.XX..",
"    XXX  .  HHHHH.   X XX X .X;HHHHz..XXX.XoX XX.....X.......  .X XXXXXXXXXXoXXXXXXoX<HHHHHH6 X . eHHHHV    X           X  XoXXXX....XXX.XX.X...O ...X.X OO .......OO...O.O..OO.XXXXXXXXO.",
"Xoo#OOOOXooXHHHHHooooO $OX XXOgHHHHrXoXX . o$oooOOXO.OO.XOOOOOOOOOX   XooOOo$XXoX XXooFHHHHHa#X.XXAHHHHd#XO+XXXXo$$oOOOXOX oo oOOXXOOOOX...OOOOOOO.OOX.. OOOOOOOO.OOO...O.OOOOOOO..XXXOOO.",
"   oXXX.X...HHHHH... . XX....XFHHHH$ ... ..XX X ......X......XXXXXX  .. XXX XX  X  oX nHHHHHpXXX <HHHHH1X. XX .XXXX  ...   OX X ......X........X.  ................O. .......O..XX.X...XX.",
"X  XXXX.    HHHHH.. ..XXX. . 9HHHHZ  .... .XX.X ......X........XX  X.  X XX o  XX  o  aHHHHHNXX  fHHHHFXX  X . X XXX.. . X oX   .....XX........X.   .....OO.......... . ........XXX...XXX.",
"   XXXX .X  HHHHHX. ...X.....lHHHHn. .... X.X   .....XXXXXXX.X.OoXX    X.XX.X..   XXX.4HHHHHMX.  VHHHHN X..X.. X XXX ...   XXXX .....XX........X... .X.. OO XX......O. .......O.O......XX.",
" XXXoXX .  XHHHHHX. .X.XX....AHHHHs...X.XXXooXXX.....XO..X.XXXX+oXX .XX XoX.+XX.XX oX.-HHHHHFoXX#HHHHHaoX .....XXXXX ....X.+o XX....XXXX..X.XX.OO...XX...OO.XXX.X..O.........O..X...X..OX.",
"   oXXX. ...HHHHHX.X.. oX...-HHHHH9........oX X .....OX........+X... . ..XX.o ..X .oX..HHHHHHXXX4HHHHH0Xo  X  .X Xo . ..   oXX X....XXX........+..  . .. .O .....  ..........X..O....XXXX.",
" X  XXXXX. .HHHHHX .X..XXX .8HHHHH4........XX . ................X.X.  . .XX.XX ....XX. FHHHHHXX.aHHHHH6XX  XXX.XXXXX....   oX X .....XX.X......X.. .......... ...  O..  .....XX....X.X.X..",
"..XOXXXX X..HHHHHX+..X.XXXXXpHHHHH>...X...XXo....X....X........XX .......XX.@X..XX.XX..NHHHHHX+.fHHHHH-XX XX..XXXXXX...XXXXoXXXX...XXXXX....X...X  ......O........ .O.. .....XX.O.XXXXXX+.",
"XXXOoX......HHHHH....X.oX.. lHHHHHX......X.o..X......XX........+X.XX.XXXX@XX+XXXXX.ooXXNHHHHHoX.NHHHHH.XXX X.XX. OXX...X.  +XX XX...XXX.X......OO .................O....O.XXXXX.O.XX.XXXXX",
"..X XXX ....HHHHH....X...X .MHHHHHX...........XX.X.X.X............X.......XX+X.X...X.. MHHHHF...MHHHHH.XX..X....XXXX.......XX..X.....X.X.......+..X..X...........  .............+XXXX.....",
".X++XoOoX++.HHHHH++++OX++X..MHHHHH@oXoo...XO+XXOO+X+XX..++++XO++XOo...++X+X+$X+X+...X++BHHHHNO+.HHHHHH+++X++...+OXXOX+OXXOXXXXO+OXOOOX+OX.XXOOO++OOXOX...+OO+++OOOO....XOOOXOO.OOX..X+O++X",
".....XX.....HHHHH..... ..X..HHHHHH....X..++.XXX.XXX..XXX...XXXX.X.X.....XX.X+.......  .MHHHHM...HHHHHH..X.........X..X..X..X.....X...XX.XXX.X.XX.X.X..XX..X...XX...............X+......X..",
"...X........HHHHH....X...X..HHHHHH..X.X.....XXXXXXXXX.X..XXXXX.X.XX........X+X..X..+...MHHHHg...HHHHHH.......X.+...X..XX..XXX.X.X.X.X..XXX.X+.XXX.XX.X.X.+X+.XXX.. OX........XXX+.X..XXX..",
"...XXXX.....HHHHH....X.XX...HHHHHH.........XX.X..X...XXX.......XXX...X...XXX+....X.XX..MHHHHpXX.HHHHHH.XX.X......XXX.......XX.X.X...XXX.....XX.X.........XO.....X..O....X....OXX+.X....XX.",
"...+XXX.....HHHHHX.....oXX..HHHHHH$.......++X.XX.....XX........++.+......+XX+...XX.OX..HHHHH4oX.HHHHHH2+XX...... +X........OX.......XXX.X...X..+X.....X..+X....XX..XX...X....XXX+...+.X+X.",
"XXX+X+X.....HHHHH....X.oX...ZHHHHH7.......X+XXX..X...+X.....X.XXX.X.XXX+XO++++XX+XX#o.XHHHHH##oXHHHHGG9O+.XXXXXXXXXX.......OX.......XOO.X...X..OX........OX.....O.XOOXXXXXXXXOXOOXX.OX++O.",
"..XXXXX.....HHHHHX.....X....MHHHHH0...X...XXX..X.....XX....X..XXXXXXXXX.XXX++...+..XX.-HHHHV.X..MHHHFDpXX.....XXXoXX...X...++..XX....XX....XXXX+X........XX.......XO.....XX.XXXXO...+..X..",
"..X+XXX...X.HHHHHX...X.XXX..MHHHHHp...+.X.XXX.XXXX...XX........X.........XXX+...XX.oX 4HHHHg.XX.MHHHHHlXX..XX..XXXXX...X..X+X...X...XXXXX...X..XX........+X........O+...X....XXX+...XX.OX.",
"...++X..X.X.HHHHH..+XX.+XX XfHHHHHn.....X.X+X.X.X....+X........X+.+......OXX+...X..+X pHHHH9.OX.lHHHHHAX+....XX+.OXX......XOO...X..X.+X.X.X.XXXOX..X.....+X........OX........OOX+X..X..+X.",
"...o+XXXXXX.HHHHH+..XXX+oXXXpHHHHHAXXXXXXXX+o.oXXX..X+X........XX.X......XXXX..XX..+XXbHHHFX.+X.aHHHHHH:O..+XX.+XO+XX..+XXXOOXXXX.X.+OXXX..XXX.OO..X.....X.........X........XXXX+X..X..+X.",
"+O##O+$O+OOXHHHHH$++OOXO+X..6HHHHHH:X+O.XXXOOo++OOX+XXX.XXO++OOOO++...++OOOO$++O+XX#OOFHHHv+O$OX7HHHHHHd$+++XXX+OOO++O++++.+XXXOOXOOOOO+X..+OOOOOOXXOX...OO+++OO+OO+X..XOOX+OO+OOXXX++O&OO",
"..X+XXXX.XX.GGHHH+...X.XXX..#HHHHHHe...X.XXXXXX.XX....X........XX.X.X...X+.++.X.X..+X,HHHH<..+X.XHHHHHHV+....XXOXXXX.......OX...X....+XXX...X.XX.........XX.....X..+X........XOX+.X.X.X+X.",
"..XXXX...X.-HHHHH.X..XX+XXX..VHHHHHb..... .oXX..X.+..XX..X...XXXX........+..++.X...XXfHHHM...XXX.NHHHHHH;........XXXXX.X...++.XXX..X.+X..X.XX..OOX........X+...X....XX.X........+XXX...X..",
"..X...X..X.4HHHHH..XXX.XX.X..gHHHHHH#.X....X.X...XXX.XX......XXX.XX.........+.XX....XAHHH5....X.XsHHHHHHz........XXXXXX....XXX..X..X.XX.XXXX...XXXX.X......+XX.X....X...........+.........",
"..X...X..X.4HHHHH....XX.XXX..,HHHHHHp.............XX.X.......XXX.X..........+.X....X8HHHN......XX-HHHHHHSO.......X.XXX.XX...X...X...........X...XX.X.......XX.......X.X+..XX....+.X.....XX",
".XX... X...5HHHHG....X.X.X....FHHHHHA+.....XX  X..X. X....X.XXXX.X..........+..X....MHHH5.......X.VHHHHHHd....X.....X.......X...X...............X..X....X XXX.XX.......XX..+.X..+.XX......",
"..XX. X.X..5HHHHH.....XoX.....aHHHHHHa... XXXX.X..XXXXX.X... XX X.......X.X.+..X...6HHHc.... X..X.wHHHHHHH-.........X..+....X...X...........X..X.XX...X.9XXXXX.XX..XX.XXX....XX.+.X....+..",
"X.XoXX.X.+X5HHHHH.XX.XX+X.....%GHHHHHFO...XXX X ..X..oX .....XXoX..X.+XXX+XX+XXX...MHHF%.+..XXXXXX+SHHHHHHM.+...XXXXX.XX...X+...X....+X....X....X.+X...9MoX+..X..XX+o.XX+.XX.++X+XXXX.XO+.",
".XXoX.XX...5HHHHH<...XX++XX.XXXzHHHHHHl...XOXXX ..XXX++....XXXX+++.......+X.X.XX..pHHH7.....XOXXX..pHHHHHHHp..XXX++XXXXXX.+++..+XXXXX++.X.XXX..OO......SMOXXXXXXX..o+X.X.....+X.X..X...+XX",
".XX+X..X.+.wHHHHH6..XXX++X.X..X%FHHHHHH8..X+oX  ..+..oX..X.. XX+XXX.X.X..+X.+X.X.,FHGsX+.. X +XXX...VHHHHHHH6...X+XXXXXX...O+....... +X XX.X...X+XXX.XpFaXXXXX.....+XXXXX ...+X.+XXX...+XX",
".+##O+OOXOOaHHHHH6+X#OX$#X..o+#OaHHHHHHF,.X##+X+#XXOoXX X++o+OOOO+X...XOOOOOO++OOVHHvO+++O+Xo#XXX++O7HHHHHHHF<XXO#OoO#OXOO.X+.+OO+o#oOOoX..+++OOOOXX+3GG;O#O+X+OX+O+X.XOO+++O#oOOXXX.OO&OO",
"XXXoXXX.X.+pHHHHH6XX.XX+XX.X..X..VHHHHHHFOXoXX.. .X.XoX..... XXX....XXXX.++.+XX&VHGc++X++.X+XoXX+....gHHHHHHHF<.XoXXXXXX..Xo+..XX. X X XX.X.X..XXX.+#VHM.+XXX ..X.XoooXX+.XX.OXX+XXX...OXX",
".X.OX...XX.aHHHHH6X..XX@+.....X..>FHHHHHGV-OX.....+..oX.....XXXO+.X...XX.O+X+X&MHHvO+.XX...X oXX..+...MHHHHHHHF,.+XXXX.X...++...X. XXOoX.......+oX..lHHw +XXXX.XX..oXXXXXXXX.OXX+XXX...O+X",
".XX+XXX.XXXbHHHHH2X.X+X++..X..X..X0HHHHHHHF<XXX...X.X+X......+X+X.XX..X..O+X+$VGFjX++.XX.X.XXOX+.XXXX.%VGHHHHHHHaoXXXX.X...OX...X...X+X XX.+...ooXXaHHZ..X+XXX.+X..X+X.+XXXX.XXXXXXXXX.+X.",
"-$.+oO--=&-BHHHHHpX$**&&;;#$*+X.X=-aHHHHHHHFa.X&-*&$;;O&&X..X&-;&&;=+==XXXO%qDGFu$O;$+.XO&&&O*;O#&O.XX#,ZHHHHHHHHb;X#&&$O&&#&&X...O&&##&#+O$+..O##pHHHi+#$X.X+O#OOO&$+#++..+O&#+&OO+OX.+O+",
"X++O+XXXXXXFHHHHHp..XXX++XX.X.XX++XXyHHHHHHHHM-....XX+XX....XXX+X+X.XXXXXO&zHHB>XXXO+XX+XXX+XO+XX++XXXXO%VHHHHHHHHHa#XXX.XX+XX.X.+.XX+X XX.....XXlHHHV..XXXX....XX.+XXX++XXXXooX+XO+XX+++X",
"...XX..X.X-HHHHHHl.XX o+XXX.XXXX.oXXXyFHHHHHHHHf-XXXX+XX+X..XX+XX.X...X.OpSFFs+X.X.XX....X..XO.......XXo.%lHHHHHHHHHFs-XX.XX+.XXX.XXXXXXXX.+...:MHHHH6+.X+XX+.+XX...XXXX. X..X.....XX..XX.",
".... ....#mHHHHHHF=. XXXXX....X...X..X3VHHHHHHHHHl8.X........XXXX.X...<lFHHz%..X................X .... X..+pFHHHHHHHHHHbw#..X..XX .X....XX.X.OaHHHHHa..+ ..X+..+. ..XXXXX.......X..X......",
"..... -ebFHHHHHHHHHHMbaw4O....X......X.XaHHHHHHHHHHFze<..X...XXX.X#9fZHHHM;X..X...................  ..XX....%lHHHHHHHHHHHHMp4#...XX.....XX;wlHHHHHHgX......XX..X+...X.XX........X.X.......",
"...<fZGHHHHHHHHHHHHHHHHHHHSj..XX.X+....X.>cHHHHHHHHHHHGHVMfpppafMAHHHHHc7.X XX..................... . X .....+-NHHHHHHHHHHHHHHFMlpppaapbMFHHHHHHHB7X.....X.+XXX+XX.XO.XXXX........X.......",
".$bHHHHHHHHHHHHHHHHHHHHHGGV4X+O++OO#X#+...+>gFHHHHHHHHHHHHHHHHHHHHHHAs>+OO++#X++...XOXOOXOOXOOX..X+O++o##++O...+>kFHHHHHHHHHHHGGHHHHHHHHHHHHHHVk>#ooOX...OOOO+OOOX+OXXX+O++OO$XOO....XOOOO",
".VFMMss077%++@+%47ppcMSFVu+...X..XXX.X...XX+++0zSDFGGHHHHHHHHHHHHNs3X....XX.X..X...XX........XXX....X..++........++7gVHHHHHHHHHHFGGHHHHHHHNgy>X++........X.++..X...XX.XXXX...+X.X......+..",
".+XOXXXX.....++...+.+++O++....X..+X ......XOX...+;qpnMVHHHHZNcs7@XX...X..XX.X......XXXX......OX..X....X++.....XX.oXX+X+7apNBFHHHFSDBMga03XXX...+X..X.....OX........OXX.XX....XX.X......XO.",
"...+X XX..X..+X.XX.X.X.+XXX...X. oX .X....+++XX.....+@+X++XX+XXXXXX...X..OX.X.XX...+X...X..X.+X........OXX..X..X.oXXXXXXX.X@++XX++++X++.+..X...o+X.X.....+XX+..X...XXXX.X...XXX.X.XX..XXX.",
"...+XX ......XX....X...+X....... oX .......X......X.XX+........+XX....X..oX..XX....XX......X.XXX.......+X........XX.X XX...XX........+..X......XX........XX....XX..+XX.XX....+XX.XX....+X.",
",*X+X&,,:-,3-;<&X.X&,,::33&;,OX.o;<,;-<<$;,#X.+-,,;-23O,;X..+;<<--3>@>;X.+$;,;-;,;$,;..XO;,;&,,*&;$X.X&,;-&;:&&;#oXX&;;&$::$;=+..X&;;&&;;+==X..#&&-OO;&O&-X..OO&&#&:*O&$X..+O-&O$&OOOO.OOX",
".+.OX ...X ..#X...X.X..OX....... OX  X....XOX.X .....OX.......++X.....X..OX.XXX....OX......X.OXX...X...+XX.X.... +X.XX.X...oXX.......OX.X......oO.XX.....OX.X.+....XXXXXX...X+X........XX.",
".+.XXXXXXX+..++..XX.XXX+XXX...XXX+XXXXXXXXXO+.X.X.X.XOX......XX++.X...X.XXX.X..X...OX....X.+XOXX.XX.X..OXXXXX.XXXOXXXXXXXXX+XXXX.X.+.O+X+XXXXXXOXXX......XXX+......XXXXXX...XXX.XXXX...XXX",
"...+XX X.XX..OX.X.XX..X+XX.XX.X.XX X o....+XXXX...XX.XX.......X+XXX...X..XX.XX......O...X..X.XX.....X.X+X.X.X...XXXXXX.XX..oX......X.+X.X..X...+X.XX.....OX.X.X+X..+X.XX.....OX.X..X...OX.",
"...O+.....XX.OXX.....XXOX.XXXXXXX+X..+....+oX.....X..OX......X+OX.+......+X.X......OX..X...XX+XX.....X.+XXXXXX.XX+XXXXX....+XX X...+XO..+......OXX.......+.XXX+.XX.XXXXXXX..XXX.X..X...XX.",
".+O#O+OOXOOXXXXOOO++OOXOOX..X+O+o##O+#+..X+##O+OOO+OX+X.+OOOOOOOO#X...++O@++#+oO...OO+OX+OO+OO+..X+OO++&OX++X.XXo##++#OoOo.oXX+OOO+OOOOO+..+OO+OOOOOOXX..OOOOOOOXX#XX..++OO+O+XOOX..XXOOOX",
"X+..XX+.+XXXXXXXX+XXXX++XXXXXXXXXXXX.++X+XO+XX+.XX+XXX........+.XXX...X.. X X.X..........X.X.X.+X.X.XXXXXXXXXXXXXXXXXXXXXXXXXXXX+.X+++X++XXX+.XXXXXXXXXX...XXXX........XX.......X..XX.....",
".X..........X.XX.XX.XX.XXXX.XXX....X.+XX.X+XX+XX+XXX+X+XXXXX++++X++...X..X XX..............X........X.XXX.XXXXX.XXXXXXXXX...XXX .X.+...XOX+X+.X+OXX+XXXX.++++++++...+..XX.......XX........",
"......................XXX.....X......+...X+..X...XX..........XX.XXX...X... XX X.....X....X.X...X............X... .....X...  X X ...XX...+...X.X.X.XXX....X..XXX....XX..XX....XX.X..X...XX.",
".X.XX........+X...X...XXXXX...X..X..XXX..XX+XX+.X..XX+........X+.X....X..XX XX.....XX........X.........X.XX......X..XX..X.XXXX.....+XXXX+..+.X.XXX..X....+.XX.XX...X+...X....+X.X......XX.",
"...+........XOX.......X+XXX..XX..OXXX+XXXXoOX+...X..X++......X.+XXXX..+.+OXXXX.X...XX......X.O.........+X..XX....oX.X..XX.Xo+.XX...+XOXX++XXX..+XX.X...X.OXXX.XXX+.O+XX+XXXXX+XXXX.X...OX.",
".XX+XX.......OX.......XOX...... .OX..XX...XOX........OX........OXX....X. +X X......XX......X.O.........OX...X....oX..XX... +X.. ...+.OX.X......OX..X.....+..XX.X...Oo.XXXXX..+XXXXX....+X.",
"...+X........+X.......X+.........+X..XX...+++........O.........OX.....X..+X.X..X...OX...XX.X.O.X...X..X+X...X....+.....X...OX......X.OX.+.XX...O....X....X..+..X...+XX.XX.X..XX.X..X...XX.",
"...XX........+.........+X........+...X....+++........+.........+XXX...X..+X..XX....XX.....X..XXX...X...+X..XX...X+..X......+.......X.++........+.........+X....XX..+XX.XX....OX..XX....OXX",
".XXOXXX...XX.O+..X...XXOX........O...O.....O.........OX........+XX....X..OX.XXXX...OXX..X..X.OXX...X...O+.XX.....OX.XX.....+X......X.+..X.XX...OXXX.....XOXX.X.+...O+XXXXX..XOX.XXXX..XO+.",
".+O&OOOO+OOX.O+OOOO+OO+&O+XXXOOOO&OO+OO...O&&OOOOOO+OOO.+OOOOO&&OOO..X+OOOOOO++OX.XOOOOOOOOOOOXX.X+OOO+&OXOOXX.+O&OOOOO+OO.OOXOOO+O&O&OO+XX+OOOOOOOOOO..+OOOOOOOO+O+XXX+OOOOOO++OX...OOOO+",
"..XXXX.......+X.......XXX..X.+...+.XXX.X.+++XXX.X.X..+..X.XXXXX++XX..XXXXO..X.XX...OXXX.XX.X.+XX.X.....+X..XX..X.+X.X.XX...O...XXX.+XOX.+..X...OXXXX+...X+XXX.X.X..+XXXXX...XXXXX.XX...+..",
".X.+X...X....+X..X....XOXXX......+XX.+XX..+OXXX......O+..XX.XXXOXXX...X.X+X.XX.X...XX....XX..+......X..+...X.XX..X..X.XX...+......XX.+X.+++XX..+X.XXX...X+XXXX.X...O+XXXXX..XOX..XX....OX.",
"XX.++........OXX....XXX+XXXX.XXXXOXXX++X.X+O+XX.XX+..O+..XX.XXXOXXXX.XX..OX.XXXXX..OX...X.XXX+XX.X..X..OXXXXXX.X.OX.XXXXX..O+..+XXX+XO+XX.+.+..O+.XXXXXXX+XX+XXXX..+XXXXX..XXXXXXXXX...+X."
]